run:
  concurrency: 4

linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - errcheck
    - ineffassign
    - gocyclo
    - unused
    - typecheck

issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - gocyclo

linters-settings:
  gocyclo:
    min-complexity: 15
  gofmt:
    simplify: true
  govet:
    enable-all: true
