// Copyright 2024 SerialLink Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: api/proto/serial.proto

package serialpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SerialService_ListPorts_FullMethodName           = "/seriallink.v1.SerialService/ListPorts"
	SerialService_GetPortInfo_FullMethodName         = "/seriallink.v1.SerialService/GetPortInfo"
	SerialService_OpenPort_FullMethodName            = "/seriallink.v1.SerialService/OpenPort"
	SerialService_ClosePort_FullMethodName           = "/seriallink.v1.SerialService/ClosePort"
	SerialService_GetPortStatus_FullMethodName       = "/seriallink.v1.SerialService/GetPortStatus"
	SerialService_Write_FullMethodName               = "/seriallink.v1.SerialService/Write"
	SerialService_Read_FullMethodName                = "/seriallink.v1.SerialService/Read"
	SerialService_StreamRead_FullMethodName          = "/seriallink.v1.SerialService/StreamRead"
	SerialService_StreamWrite_FullMethodName         = "/seriallink.v1.SerialService/StreamWrite"
	SerialService_BiDirectionalStream_FullMethodName = "/seriallink.v1.SerialService/BiDirectionalStream"
	SerialService_ConfigurePort_FullMethodName       = "/seriallink.v1.SerialService/ConfigurePort"
	SerialService_GetPortConfig_FullMethodName       = "/seriallink.v1.SerialService/GetPortConfig"
	SerialService_Ping_FullMethodName                = "/seriallink.v1.SerialService/Ping"
	SerialService_GetAgentInfo_FullMethodName        = "/seriallink.v1.SerialService/GetAgentInfo"
)

// SerialServiceClient is the client API for SerialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SerialService provides serial port management and communication operations
type SerialServiceClient interface {
	// Port Discovery
	ListPorts(ctx context.Context, in *ListPortsRequest, opts ...grpc.CallOption) (*ListPortsResponse, error)
	GetPortInfo(ctx context.Context, in *GetPortInfoRequest, opts ...grpc.CallOption) (*PortInfo, error)
	// Port Management
	OpenPort(ctx context.Context, in *OpenPortRequest, opts ...grpc.CallOption) (*OpenPortResponse, error)
	ClosePort(ctx context.Context, in *ClosePortRequest, opts ...grpc.CallOption) (*ClosePortResponse, error)
	GetPortStatus(ctx context.Context, in *GetPortStatusRequest, opts ...grpc.CallOption) (*PortStatus, error)
	// Data Transfer
	Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	// Streaming
	StreamRead(ctx context.Context, in *StreamReadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error)
	StreamWrite(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DataChunk, StreamWriteResponse], error)
	BiDirectionalStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DataChunk, DataChunk], error)
	// Port Configuration
	ConfigurePort(ctx context.Context, in *ConfigurePortRequest, opts ...grpc.CallOption) (*ConfigurePortResponse, error)
	GetPortConfig(ctx context.Context, in *GetPortConfigRequest, opts ...grpc.CallOption) (*PortConfig, error)
	// Health & Diagnostics
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	GetAgentInfo(ctx context.Context, in *GetAgentInfoRequest, opts ...grpc.CallOption) (*AgentInfo, error)
}

type serialServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSerialServiceClient(cc grpc.ClientConnInterface) SerialServiceClient {
	return &serialServiceClient{cc}
}

func (c *serialServiceClient) ListPorts(ctx context.Context, in *ListPortsRequest, opts ...grpc.CallOption) (*ListPortsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPortsResponse)
	err := c.cc.Invoke(ctx, SerialService_ListPorts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serialServiceClient) GetPortInfo(ctx context.Context, in *GetPortInfoRequest, opts ...grpc.CallOption) (*PortInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PortInfo)
	err := c.cc.Invoke(ctx, SerialService_GetPortInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serialServiceClient) OpenPort(ctx context.Context, in *OpenPortRequest, opts ...grpc.CallOption) (*OpenPortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenPortResponse)
	err := c.cc.Invoke(ctx, SerialService_OpenPort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serialServiceClient) ClosePort(ctx context.Context, in *ClosePortRequest, opts ...grpc.CallOption) (*ClosePortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClosePortResponse)
	err := c.cc.Invoke(ctx, SerialService_ClosePort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serialServiceClient) GetPortStatus(ctx context.Context, in *GetPortStatusRequest, opts ...grpc.CallOption) (*PortStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PortStatus)
	err := c.cc.Invoke(ctx, SerialService_GetPortStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serialServiceClient) Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, SerialService_Write_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serialServiceClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, SerialService_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serialServiceClient) StreamRead(ctx context.Context, in *StreamReadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SerialService_ServiceDesc.Streams[0], SerialService_StreamRead_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamReadRequest, DataChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SerialService_StreamReadClient = grpc.ServerStreamingClient[DataChunk]

func (c *serialServiceClient) StreamWrite(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DataChunk, StreamWriteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SerialService_ServiceDesc.Streams[1], SerialService_StreamWrite_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DataChunk, StreamWriteResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SerialService_StreamWriteClient = grpc.ClientStreamingClient[DataChunk, StreamWriteResponse]

func (c *serialServiceClient) BiDirectionalStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DataChunk, DataChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SerialService_ServiceDesc.Streams[2], SerialService_BiDirectionalStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DataChunk, DataChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SerialService_BiDirectionalStreamClient = grpc.BidiStreamingClient[DataChunk, DataChunk]

func (c *serialServiceClient) ConfigurePort(ctx context.Context, in *ConfigurePortRequest, opts ...grpc.CallOption) (*ConfigurePortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigurePortResponse)
	err := c.cc.Invoke(ctx, SerialService_ConfigurePort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serialServiceClient) GetPortConfig(ctx context.Context, in *GetPortConfigRequest, opts ...grpc.CallOption) (*PortConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PortConfig)
	err := c.cc.Invoke(ctx, SerialService_GetPortConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serialServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, SerialService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serialServiceClient) GetAgentInfo(ctx context.Context, in *GetAgentInfoRequest, opts ...grpc.CallOption) (*AgentInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentInfo)
	err := c.cc.Invoke(ctx, SerialService_GetAgentInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SerialServiceServer is the server API for SerialService service.
// All implementations must embed UnimplementedSerialServiceServer
// for forward compatibility.
//
// SerialService provides serial port management and communication operations
type SerialServiceServer interface {
	// Port Discovery
	ListPorts(context.Context, *ListPortsRequest) (*ListPortsResponse, error)
	GetPortInfo(context.Context, *GetPortInfoRequest) (*PortInfo, error)
	// Port Management
	OpenPort(context.Context, *OpenPortRequest) (*OpenPortResponse, error)
	ClosePort(context.Context, *ClosePortRequest) (*ClosePortResponse, error)
	GetPortStatus(context.Context, *GetPortStatusRequest) (*PortStatus, error)
	// Data Transfer
	Write(context.Context, *WriteRequest) (*WriteResponse, error)
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	// Streaming
	StreamRead(*StreamReadRequest, grpc.ServerStreamingServer[DataChunk]) error
	StreamWrite(grpc.ClientStreamingServer[DataChunk, StreamWriteResponse]) error
	BiDirectionalStream(grpc.BidiStreamingServer[DataChunk, DataChunk]) error
	// Port Configuration
	ConfigurePort(context.Context, *ConfigurePortRequest) (*ConfigurePortResponse, error)
	GetPortConfig(context.Context, *GetPortConfigRequest) (*PortConfig, error)
	// Health & Diagnostics
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	GetAgentInfo(context.Context, *GetAgentInfoRequest) (*AgentInfo, error)
	mustEmbedUnimplementedSerialServiceServer()
}

// UnimplementedSerialServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSerialServiceServer struct{}

func (UnimplementedSerialServiceServer) ListPorts(context.Context, *ListPortsRequest) (*ListPortsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPorts not implemented")
}
func (UnimplementedSerialServiceServer) GetPortInfo(context.Context, *GetPortInfoRequest) (*PortInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPortInfo not implemented")
}
func (UnimplementedSerialServiceServer) OpenPort(context.Context, *OpenPortRequest) (*OpenPortResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenPort not implemented")
}
func (UnimplementedSerialServiceServer) ClosePort(context.Context, *ClosePortRequest) (*ClosePortResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClosePort not implemented")
}
func (UnimplementedSerialServiceServer) GetPortStatus(context.Context, *GetPortStatusRequest) (*PortStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPortStatus not implemented")
}
func (UnimplementedSerialServiceServer) Write(context.Context, *WriteRequest) (*WriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedSerialServiceServer) Read(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedSerialServiceServer) StreamRead(*StreamReadRequest, grpc.ServerStreamingServer[DataChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamRead not implemented")
}
func (UnimplementedSerialServiceServer) StreamWrite(grpc.ClientStreamingServer[DataChunk, StreamWriteResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamWrite not implemented")
}
func (UnimplementedSerialServiceServer) BiDirectionalStream(grpc.BidiStreamingServer[DataChunk, DataChunk]) error {
	return status.Error(codes.Unimplemented, "method BiDirectionalStream not implemented")
}
func (UnimplementedSerialServiceServer) ConfigurePort(context.Context, *ConfigurePortRequest) (*ConfigurePortResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigurePort not implemented")
}
func (UnimplementedSerialServiceServer) GetPortConfig(context.Context, *GetPortConfigRequest) (*PortConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPortConfig not implemented")
}
func (UnimplementedSerialServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedSerialServiceServer) GetAgentInfo(context.Context, *GetAgentInfoRequest) (*AgentInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentInfo not implemented")
}
func (UnimplementedSerialServiceServer) mustEmbedUnimplementedSerialServiceServer() {}
func (UnimplementedSerialServiceServer) testEmbeddedByValue()                       {}

// UnsafeSerialServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SerialServiceServer will
// result in compilation errors.
type UnsafeSerialServiceServer interface {
	mustEmbedUnimplementedSerialServiceServer()
}

func RegisterSerialServiceServer(s grpc.ServiceRegistrar, srv SerialServiceServer) {
	// If the following call panics, it indicates UnimplementedSerialServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SerialService_ServiceDesc, srv)
}

func _SerialService_ListPorts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPortsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SerialServiceServer).ListPorts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SerialService_ListPorts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SerialServiceServer).ListPorts(ctx, req.(*ListPortsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SerialService_GetPortInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPortInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SerialServiceServer).GetPortInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SerialService_GetPortInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SerialServiceServer).GetPortInfo(ctx, req.(*GetPortInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SerialService_OpenPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenPortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SerialServiceServer).OpenPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SerialService_OpenPort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SerialServiceServer).OpenPort(ctx, req.(*OpenPortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SerialService_ClosePort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClosePortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SerialServiceServer).ClosePort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SerialService_ClosePort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SerialServiceServer).ClosePort(ctx, req.(*ClosePortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SerialService_GetPortStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPortStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SerialServiceServer).GetPortStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SerialService_GetPortStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SerialServiceServer).GetPortStatus(ctx, req.(*GetPortStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SerialService_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SerialServiceServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SerialService_Write_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SerialServiceServer).Write(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SerialService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SerialServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SerialService_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SerialServiceServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SerialService_StreamRead_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamReadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SerialServiceServer).StreamRead(m, &grpc.GenericServerStream[StreamReadRequest, DataChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SerialService_StreamReadServer = grpc.ServerStreamingServer[DataChunk]

func _SerialService_StreamWrite_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SerialServiceServer).StreamWrite(&grpc.GenericServerStream[DataChunk, StreamWriteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SerialService_StreamWriteServer = grpc.ClientStreamingServer[DataChunk, StreamWriteResponse]

func _SerialService_BiDirectionalStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SerialServiceServer).BiDirectionalStream(&grpc.GenericServerStream[DataChunk, DataChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SerialService_BiDirectionalStreamServer = grpc.BidiStreamingServer[DataChunk, DataChunk]

func _SerialService_ConfigurePort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigurePortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SerialServiceServer).ConfigurePort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SerialService_ConfigurePort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SerialServiceServer).ConfigurePort(ctx, req.(*ConfigurePortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SerialService_GetPortConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPortConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SerialServiceServer).GetPortConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SerialService_GetPortConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SerialServiceServer).GetPortConfig(ctx, req.(*GetPortConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SerialService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SerialServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SerialService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SerialServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SerialService_GetAgentInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SerialServiceServer).GetAgentInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SerialService_GetAgentInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SerialServiceServer).GetAgentInfo(ctx, req.(*GetAgentInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SerialService_ServiceDesc is the grpc.ServiceDesc for SerialService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SerialService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seriallink.v1.SerialService",
	HandlerType: (*SerialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPorts",
			Handler:    _SerialService_ListPorts_Handler,
		},
		{
			MethodName: "GetPortInfo",
			Handler:    _SerialService_GetPortInfo_Handler,
		},
		{
			MethodName: "OpenPort",
			Handler:    _SerialService_OpenPort_Handler,
		},
		{
			MethodName: "ClosePort",
			Handler:    _SerialService_ClosePort_Handler,
		},
		{
			MethodName: "GetPortStatus",
			Handler:    _SerialService_GetPortStatus_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _SerialService_Write_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _SerialService_Read_Handler,
		},
		{
			MethodName: "ConfigurePort",
			Handler:    _SerialService_ConfigurePort_Handler,
		},
		{
			MethodName: "GetPortConfig",
			Handler:    _SerialService_GetPortConfig_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _SerialService_Ping_Handler,
		},
		{
			MethodName: "GetAgentInfo",
			Handler:    _SerialService_GetAgentInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamRead",
			Handler:       _SerialService_StreamRead_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamWrite",
			Handler:       _SerialService_StreamWrite_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "BiDirectionalStream",
			Handler:       _SerialService_BiDirectionalStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/serial.proto",
}
